version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  assignees:
  - vnegrisolo
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.24.0
    - 0.24.1
  - dependency-name: credo
    versions:
    - 1.5.4
